Tensors are main building blocks of Machine Learning.

Pytorch tensor are created using torch.tensor() , you can refer this https://pytorch.org/docs/stable/tensors.html#id9 document for more details. This site represent with picture https://www.linkedin.com/pulse/machine-learning-basics-scalars-vectors-matrices-tensors-prasad/

In [ ]:
import torch
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import torchinfo,torchmetrics


In [265]:
SCALAR = torch.tensor([10])
print(SCALAR) # just print the tensor
print(SCALAR.item()) # print the value of the tensor
print(SCALAR.ndim) # print the number of dimensions
print(SCALAR.size()) # print the size of the tensor



tensor([10])
10
1
torch.Size([1])


In [267]:
VECTOR = torch.tensor([10,20,30,40])
print(VECTOR) # just print the tensor
#print(vector.item()) # print the value of the tensor
print(VECTOR.ndim) # print the number of dimensions
print(VECTOR.size()) # print the size of the tensor
print(VECTOR.shape) # print the size of the tensor
print(VECTOR[2:]) # print the first element of the tensor


tensor([10, 20, 30, 40])
1
torch.Size([4])
torch.Size([4])
tensor([30, 40])


In [268]:
MATRIX = torch.tensor([[7,10],[4,3],[5,1]])
print(MATRIX) # just print the tensor
#print(matrix.item()) # print the value of the tensor
print(MATRIX.ndim) # print the number of dimensions
print(MATRIX.size()) # print the size of the tensor
print(MATRIX.shape) # print the size of the tensor
print(MATRIX[2:]) # print the first element of the tensor 
print(MATRIX[2][1]) # print the first element of the tensor  

tensor([[ 7, 10],
        [ 4,  3],
        [ 5,  1]])
2
torch.Size([3, 2])
torch.Size([3, 2])
tensor([[5, 1]])
tensor(1)


In [266]:
MATRIX = torch.tensor([[10,20,30,40],[50,60,70,80],[90,100,110,120]])

print(MATRIX) # just print the tensor
#print(MATRIX.item()) # print the value of the tensor
print(MATRIX.ndim) # print the number of dimensions
print(MATRIX.size()) # print the size of the tensor
#print(MATRIX.shape) # print the size of the tensor
print(MATRIX[2]) # print the first element of the tensor

tensor([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])
2
torch.Size([3, 4])
tensor([ 90, 100, 110, 120])


In [269]:
TENSOR = torch.tensor([[[[1,2,3],[3,4,5],[6,7,8]]]])
print(TENSOR) # just print the tensor
print(TENSOR.ndim) # print the number of dimensions
print(TENSOR.shape) # print the size of the tensor

tensor([[[[1, 2, 3],
          [3, 4, 5],
          [6, 7, 8]]]])
4
torch.Size([1, 1, 3, 3])


In [ ]:
TENSOR = torch.tensor([ [[[5,1,3],[5,1,3]]] ])
print(TENSOR) # just print the tensor
print(TENSOR.ndim) # print the number of dimensions
print(TENSOR.shape) # print the size of the tensor
print(TENSOR[0][0][0][2]) # print the first element of the tensor

In [ ]:
TENSOR = torch.tensor([[[[[1,2],[3,4],[6,7],[6,7]]]]])
print(TENSOR) # just print the tensor
print(TENSOR.ndim) # print the number of dimensions
print(TENSOR.shape) # print the size of the tensor
print(TENSOR[0][0][0][2][0])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[6,7,8]]])
#print(TENSOR) # just print the tensor
#print(TENSOR.item()) # print the value of the tensor
print(TENSOR.ndim) # print the number of dimensions
print(TENSOR.shape) # print the size of the tensor
#print(TENSOR[2]) # print the first element of the tensor

### Tips to find the ndim & shape:
ndim --> Just count the brackets
shape -->consider each bracket is 1 till (just before the brackets holding another set of array values) and then count array as whole and each number count in it.
To reterive: Consider Zeroth position each bracket, once reached the position with array of values then counts starts 0, 1, 2,

Example:

[[10,20]] 

ndim = 2

shape = 1,2

[[10,20,30,40],[50,60,70,80],[90,100,110,120]] 

ndim = 2

shape = 3,4

[[[[[1,2],[3,4],[6,7],[6,7]]]]]

ndim = 5

shape = 1,1,1,4,2
